project:
  type: website
  output-dir: docs

website:
  title: "Ananya's Portfolio"
  favicon: favicon.ico
  navbar:
    logo: image/logo.png
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - href: projects/index.qmd
        text: Projects
      - href: cv/cv.qmd
        text: CV
        target: _blank
      - text: GitHub
        href: https://github.com/AnanyaMahadeva
        target: _blank
      - href: reflection.qmd 
        text: Reflection
      - href: contact.qmd
        text: Contact
  
  page-footer:
    center: |
      © 2026 Ananya Mahadeva | Built with Quarto     

format:
  html:
    theme: cosmo
    css: styles.scss